import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import HeaderMenu from "@/components/Headers/headerMenu";
import Footer from "@/components/Footer/footer"; // Importe o Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RPGo!",
  icons: {
    icon: "/img/icone.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gray-800`}
      >
        <HeaderMenu />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}